#Don't Change anything here
name: zcart
description: A multivendor E commerce App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


#Only Chnage this value to update your version
#1.0.0 is version number and 1 is build number
version: 1.0.0+1


#Don't Change Anything From here
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.12.1
  http: 0.12.1
  flutter_widget_from_html: ^0.5.2+1
  carousel_slider: ^2.3.1
  flutter_rating_bar: ^4.0.0
  shimmer: ^1.1.2
  flutter_slidable: ^0.6.0
  nb_utils: ^4.2.3
  velocity_x: ^1.4.1
  share: ^2.0.1
  datetime_picker_formfield: ^1.0.0
  flutter_countdown_timer: ^4.1.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^1.1.2
  flutter_spinkit: ^4.1.2+1
  cupertino_icons: ^1.0.0
  animations: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/


